
#define        F_CPU           (8000000UL) 

#define OSCCAL_CALIBRATION			1
#define OSCCAL_FORCE_CALIBRATION	1

#define UART0_RX_PIN		PA5
#define UART0_TX_PIN		PA6
#define UART0_DDR			DDRA
#define UART0_PORT			PORTA
#define UART0_PIN			PINA
#define UART0_BAUDRATE		9600

#define UART1_RX_PIN		PA0
#define UART1_TX_PIN		PA1
#define UART1_DDR			DDRA
#define UART1_PORT			PORTA
#define UART1_PIN			PINA
#define UART1_BAUDRATE		9600